[package]
name = "moix-cli"
version = "0.0.1"
edition = "2024"

[dependencies]
base64 = "0.23"
brotli = "9.0"
dotenvy = "0.15"
html-minifier = "5.0"
minreq = { version = "3.0", features = ["https-native-tls"] }
walkdir = "2.5"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
overflow-checks = false
